apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: my-cronjob
spec:
  schedule: "*/1 * * * *"
  concurrencyPolicy: Allow
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: my-cronjob
              image: cronjob
              command:
                - "/usr/bin/python3"
                - "/app/cron.py"
          restartPolicy: OnFailure
